/* 
 * Write a java program that will read a customer’s number and name, a sales amount and a tax
 * code before preparing a sales report for Hashim Hardware Sdn Bhd. The tax code is to be applied
 * to the sales amount to determine the sales tax due for that sale, as follows:
 * The report is to print a heading ‘SALES REPORT’, and detail lines listing the customer number,
 * name, sales amount, sales tax and the total amount owing.
 */

//Name:             LIM JUN YI
//Class:            F2T9
//Matric Number:    MS2124135403

//THE CODE STARTS HERE//

//import modules from library
import java.util.Scanner;
import java.text.DecimalFormat;

class LimJunYi_F2T9{

    public static void main(String[] args){

        //Local Initialisations
        Scanner sc = new Scanner(System.in);
        DecimalFormat df = new DecimalFormat("#,###,##0.00");
        double salesAmount, salesTax, salesTotal, taxDecimal;
        int taxCode, customerNumber, taxPercentage = 0;
        String customerName, salesAmountFormatted, salesTaxFormatted, salesTotalFormatted;
        boolean loopOperation = false;

        //Reloop if user entered invalid taxCode
        do{

            //Output Format - Header
            System.out.println("\n================== HASHIM HARDWARE ==================\n");
            
            //Input Section - Read user input
            System.out.print("[Customer Number]        : ");
            customerNumber = sc.nextInt();
            System.out.print("[Customer Name]          : ");
            sc.nextLine(); /*clear buffer, that's because the sc.nextInt method does not read the newline 
            character in your input created by hitting "Enter," and so the call to sc.nextLine returns 
            after reading that newline.*/
            customerName = sc.nextLine();
            System.out.print("[Sales Amount]           : RM ");
            salesAmount = sc.nextDouble();
            System.out.print("[Tax Code (0 or 1 or 2)] : "); 
            taxCode = sc.nextInt();

            //Calculations Section 01 - Determine taxPercentage
            if(taxCode == 0){
                taxPercentage = 0;
            }
            else if(taxCode == 1){
                taxPercentage = 3;
            }
            else if(taxCode == 2){
                taxPercentage = 5;
            }
            else{                                  //allow users to reenter values if taxCode is not 0 / 1 / 2
                loopOperation = true;              
                System.out.print("\033[H\033[2J"); //clears screen step 1
                System.out.flush();                //clears screen step 2
                System.out.println("[!!! The tax code is invalid !!!]\n");
                System.out.println("[!!! ENTER THE VALUESS AGAIN !!!]\n\n\n");
            }
        }
        while(loopOperation == true);
        
        //Calculations Section 02 - Determine salesTax and salesTotal
        taxDecimal = taxPercentage / 100.0;
        salesTax = salesAmount * taxDecimal;
        salesTotal = salesAmount + salesTax;

        //Calculations Section 03 - Decimal formatting
        salesAmountFormatted = df.format(salesAmount);
        salesTaxFormatted = df.format(salesTax);
        salesTotalFormatted = df.format(salesTotal);

        //Output Format - Body
        System.out.println("\n]===================[SALES REPORT]==================[\n");

        //Display Section 01 - Display Content
        System.out.println("[CUSTOMER NUMBER] : " + customerNumber);
        System.out.println("[CUSTOMER NAME]   : " + customerName);
        System.out.println("[SALES AMOUNT]    : RM " + salesAmountFormatted);
        System.out.println("[SALES TAX]       : RM " + salesTaxFormatted);
        System.out.println("[TOTAL AMOUNT]    : RM " + salesTotalFormatted);

        //Output Format - Footer
        System.out.println("\n================== HASHIM HARDWARE ==================\n");
        System.out.println("[Report Generated By LIM JUN YI]\n");

        //Prevent resource leak for scanner
        sc.close();
    }
}